// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyB5dhwwg_S5IqYiEGgZMeyrM-7vBNhCbo0',
    appId: '1:405028735635:web:9696c3b900c7517be65b66',
    messagingSenderId: '405028735635',
    projectId: 'toopoptech-d6970',
    authDomain: 'toopoptech-d6970.firebaseapp.com',
    storageBucket: 'toopoptech-d6970.appspot.com',
    measurementId: 'G-4M16CMWE9W',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyChLUj0dBIs6-ug6q0NueDXdd-kvm0D7EY',
    appId: '1:405028735635:android:850aa75fabde8f9de65b66',
    messagingSenderId: '405028735635',
    projectId: 'toopoptech-d6970',
    storageBucket: 'toopoptech-d6970.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyDyWlnKxoRfI0Kc9dWmkCghBzV2mBGE24I',
    appId: '1:405028735635:ios:6c300fbfc4f4d61de65b66',
    messagingSenderId: '405028735635',
    projectId: 'toopoptech-d6970',
    storageBucket: 'toopoptech-d6970.appspot.com',
    iosClientId:
        '405028735635-isqfv9j1o58bjliplstifkr891h2r2h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.carsStore',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyDyWlnKxoRfI0Kc9dWmkCghBzV2mBGE24I',
    appId: '1:405028735635:ios:a4a9cf511144240be65b66',
    messagingSenderId: '405028735635',
    projectId: 'toopoptech-d6970',
    storageBucket: 'toopoptech-d6970.appspot.com',
    iosClientId:
        '405028735635-e38rsli1jos5m5ov812ecbjqgpatalt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.carsStore.RunnerTests',
  );
}
